### ISSUE TITLE
Missing selection in alpha evolution?

### ISSUE THREAD

**Issue by mhinsch** [heibaihe/EpidemicSpreadingUnderMutation#1]
If I understand the programs that generate the phase diagram correctly `X` is used to simulate positive selection. So for example in lines 188-205 of PhaseDiagramSIS_alpha.cpp a normal distribution is simulated by  calculating the sum of 12 uniform distributions in `d` (and subtracting 6 to set the mean to 0). Then in the lines
```C
d = X+d*sigma;
Psi[i] = Psi[i]+d; 
```
the normal distributed value in `d` is scaled by mutation rate `sigma` and added to `X` which should be positive to simulate intra-host selection as described in the paper. In all four programs `X` is set to 0, however and never changed afterwards.

**Comment by heibaihe** [comment]
Hi,


If you read the entire loop, you will see that X is not set to 0, it we set  Psi[i] (not X) to 0 only when Psi[i] is smaller than 0 to keep the fitness positive. And this random walk is perform in the loops of i and t, so for each individual at each time step, we perform a random walk of the fitness, therefore the fitness Psi[i] will change at each time step.
















At 2022-12-06 19:32:15, "Martin Hinsch" ***@***.***> wrote:

If I understand the programs that generate the phase diagram correctly X is used to simulate positive selection. So for example in lines 188-205 of PhaseDiagramSIS_alpha.cpp a normal distribution is simulated by calculating the sum of 12 uniform distributions in d (and subtracting 6 to set the mean to 0). Then in the lines

d = X+d*sigma;
Psi[i] = Psi[i]+d; 

the normal distributed value in d is scaled by mutation rate sigma and added to X which should be positive to simulate intra-host selection as described in the paper. In all four programs X is set to 0, however and never changed afterwards.

**Comment by mhinsch** [comment]
Right, I just realised that I mixed up alpha/beta and psi/phi. Since we are only looking at psi here of course there is no intra-host evolution. And inter-host evolution happens via infection and recovery, respectively.
